# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='mobile_num',
            new_name='mobile_number',
        ),
    ]
