# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170130_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='sponsor_image',
            field=models.ImageField(upload_to='sponsors/'),
        ),
    ]
